# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1167, 912)
        self.loadRazdachaBtn = QtWidgets.QPushButton(Dialog)
        self.loadRazdachaBtn.setGeometry(QtCore.QRect(792, 60, 121, 51))
        self.loadRazdachaBtn.setObjectName("loadRazdachaBtn")
        self.loadHappyBtn = QtWidgets.QPushButton(Dialog)
        self.loadHappyBtn.setGeometry(QtCore.QRect(790, 200, 121, 51))
        self.loadHappyBtn.setObjectName("loadHappyBtn")
        self.table_2 = QtWidgets.QTableWidget(Dialog)
        self.table_2.setGeometry(QtCore.QRect(20, 400, 751, 241))
        self.table_2.setObjectName("table_2")
        self.table_2.setColumnCount(0)
        self.table_2.setRowCount(0)
        self.table_3 = QtWidgets.QTableWidget(Dialog)
        self.table_3.setGeometry(QtCore.QRect(20, 690, 751, 211))
        self.table_3.setObjectName("table_3")
        self.table_3.setColumnCount(0)
        self.table_3.setRowCount(0)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 380, 371, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(30, 10, 441, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(30, 660, 371, 16))
        self.label_3.setObjectName("label_3")
        self.saveRazdachaBtn = QtWidgets.QPushButton(Dialog)
        self.saveRazdachaBtn.setGeometry(QtCore.QRect(790, 140, 121, 41))
        self.saveRazdachaBtn.setObjectName("saveRazdachaBtn")
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(10, 50, 761, 321))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tableView = QtWidgets.QTableView(self.tab)
        self.tableView.setGeometry(QtCore.QRect(20, 10, 721, 271))
        self.tableView.setObjectName("tableView")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.makeGreenButton = QtWidgets.QPushButton(Dialog)
        self.makeGreenButton.setGeometry(QtCore.QRect(950, 70, 111, 41))
        self.makeGreenButton.setObjectName("makeGreenButton")
        self.makeYellowButton = QtWidgets.QPushButton(Dialog)
        self.makeYellowButton.setGeometry(QtCore.QRect(950, 130, 111, 41))
        self.makeYellowButton.setObjectName("makeYellowButton")
        self.makeRedButton = QtWidgets.QPushButton(Dialog)
        self.makeRedButton.setGeometry(QtCore.QRect(950, 200, 111, 41))
        self.makeRedButton.setObjectName("makeRedButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.loadRazdachaBtn.setText(_translate("Dialog", "Загрузить раздачу"))
        self.loadHappyBtn.setText(_translate("Dialog", "Загрузить Happy"))
        self.label.setText(_translate("Dialog", "Happy 2021.xlsx"))
        self.label_2.setText(_translate("Dialog", "РАЗДАЧА 2021.xlsx"))
        self.label_3.setText(_translate("Dialog", "Результат"))
        self.saveRazdachaBtn.setText(_translate("Dialog", "Сохранить раздачу"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Tab 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Tab 2"))
        self.makeGreenButton.setText(_translate("Dialog", "Сделать зеленой"))
        self.makeYellowButton.setText(_translate("Dialog", "Сделать желтой"))
        self.makeRedButton.setText(_translate("Dialog", "Сделать красной"))
