# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(932, 912)
        self.loadRazdachaBtn = QtWidgets.QPushButton(Dialog)
        self.loadRazdachaBtn.setGeometry(QtCore.QRect(792, 60, 121, 51))
        self.loadRazdachaBtn.setObjectName("loadRazdachaBtn")
        self.loadHappyBtn = QtWidgets.QPushButton(Dialog)
        self.loadHappyBtn.setGeometry(QtCore.QRect(790, 200, 121, 51))
        self.loadHappyBtn.setObjectName("loadHappyBtn")
        self.table = QtWidgets.QTableWidget(Dialog)
        self.table.setGeometry(QtCore.QRect(20, 40, 751, 331))
        self.table.setObjectName("table")
        self.table.setColumnCount(0)
        self.table.setRowCount(0)
        self.table_2 = QtWidgets.QTableWidget(Dialog)
        self.table_2.setGeometry(QtCore.QRect(20, 400, 751, 241))
        self.table_2.setObjectName("table_2")
        self.table_2.setColumnCount(0)
        self.table_2.setRowCount(0)
        self.table_3 = QtWidgets.QTableWidget(Dialog)
        self.table_3.setGeometry(QtCore.QRect(20, 690, 751, 211))
        self.table_3.setObjectName("table_3")
        self.table_3.setColumnCount(0)
        self.table_3.setRowCount(0)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 380, 371, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(30, 10, 441, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(30, 660, 371, 16))
        self.label_3.setObjectName("label_3")
        self.saveRazdachaBtn = QtWidgets.QPushButton(Dialog)
        self.saveRazdachaBtn.setGeometry(QtCore.QRect(790, 140, 121, 41))
        self.saveRazdachaBtn.setObjectName("saveRazdachaBtn")
        self.saveHappyBtn = QtWidgets.QPushButton(Dialog)
        self.saveHappyBtn.setGeometry(QtCore.QRect(790, 270, 121, 41))
        self.saveHappyBtn.setObjectName("saveHappyBtn")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.loadRazdachaBtn.setText(_translate("Dialog", "Загрузить раздачу"))
        self.loadHappyBtn.setText(_translate("Dialog", "Загрузить Happy"))
        self.label.setText(_translate("Dialog", "Happy 2021.xlsx"))
        self.label_2.setText(_translate("Dialog", "РАЗДАЧА 2021.xlsx"))
        self.label_3.setText(_translate("Dialog", "Результат"))
        self.saveRazdachaBtn.setText(_translate("Dialog", "Сохранить раздачу"))
        self.saveHappyBtn.setText(_translate("Dialog", "Сохранить Happy"))
